version: "3.7"

services:
    nginx:
        image: nginx:1.13.7
        container_name: nginx
        depends_on:
            - flask-app
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - backend
        ports:
            - "80:80"

    flask-app:
        container_name: flask-app
        build: app
        restart: always
        ports:
            - "8080:5000"
        volumes:
            - ./app:/app
        networks:
            backend:
                aliases:
                    - flask-app

    mysql-db:
        container_name: mysql-db
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: users
        ports:
            - "3308:3306"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./database:/var/lib/mysql
        networks:
            - backend

networks:
    backend:
      driver: bridge

volumes:
    app:
    database: